/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import Classes.*;
import static Telas.Inicio.init;
import static Telas.Inicio.listaMembros;
import static Telas.Inicio.cdtProjeto;
import static Telas.Inicio.listaMembros;
import static Telas.Inicio.usuario;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lucas
 */
public class CadastroMembro extends javax.swing.JFrame {
    
    String botao;
    boolean novoCadastro = false;
    static int tipo = 0;
    /**
     * Creates new form CadastroMembr
     */
    public CadastroMembro() {
        initComponents();
        
        btnCancelarMembro.setEnabled(true);
        btnOkMembro.setEnabled(true);
        BtnMudarSenha.setEnabled(true);
        if(usuario != null){
        if (usuario.getDiretoriaMembro().equals("Diretoria")){
            BtnEditarMembro.setEnabled(true);
        }else{
            BtnEditarMembro.setEnabled(false);
        }
        }
        txtNome.setEnabled(true);
        txtMatricula.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSenha.setEnabled(true);
        
        txtNome.requestFocus();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        painelInfo = new javax.swing.JPanel();
        nomeLabel = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        matriculaLabel = new javax.swing.JLabel();
        txtMatricula = new javax.swing.JTextField();
        diretoriaLabel = new javax.swing.JLabel();
        diretoriaBox = new javax.swing.JComboBox<>();
        emailLabel = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        senhaLabe = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnOkMembro = new javax.swing.JButton();
        btnCancelarMembro = new javax.swing.JButton();
        BtnEditarMembro = new javax.swing.JButton();
        BtnMudarSenha = new javax.swing.JButton();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setBackground(new java.awt.Color(89, 89, 94));

        painelTitulo.setBackground(new java.awt.Color(204, 204, 204));
        painelTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblTitulo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Cadastro Membro");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelInfo.setBackground(new java.awt.Color(121, 121, 134));
        painelInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        nomeLabel.setText("Nome do membro:");

        txtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        matriculaLabel.setText("Matricula:");

        txtMatricula.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        diretoriaLabel.setText("Diretoria:");
        diretoriaLabel.setToolTipText("");

        diretoriaBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Inovação", "Comercial", "Operações", "Diretoria", "Gerencia" }));
        diretoriaBox.setToolTipText("");
        diretoriaBox.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        diretoriaBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diretoriaBoxActionPerformed(evt);
            }
        });

        emailLabel.setText("Email institucional:");

        txtEmail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        senhaLabe.setText("Senha:");

        txtSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnOkMembro.setText("Ok");
        btnOkMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkMembroActionPerformed(evt);
            }
        });

        btnCancelarMembro.setText("Cancelar");
        btnCancelarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMembroActionPerformed(evt);
            }
        });

        BtnEditarMembro.setText("Editar Membro");
        BtnEditarMembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarMembroActionPerformed(evt);
            }
        });

        BtnMudarSenha.setText("Mudar senha");
        BtnMudarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMudarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelInfoLayout = new javax.swing.GroupLayout(painelInfo);
        painelInfo.setLayout(painelInfoLayout);
        painelInfoLayout.setHorizontalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addComponent(senhaLabe)
                        .addGap(27, 27, 27)
                        .addComponent(txtSenha))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(matriculaLabel)
                            .addComponent(diretoriaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMatricula, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(diretoriaBox, javax.swing.GroupLayout.Alignment.LEADING, 0, 312, Short.MAX_VALUE)
                            .addComponent(txtNome)))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addComponent(emailLabel)
                        .addGap(18, 18, 18)
                        .addComponent(txtEmail)))
                .addGap(51, 51, 51)
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnEditarMembro)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancelarMembro)
                            .addComponent(btnOkMembro)
                            .addComponent(BtnMudarSenha))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        painelInfoLayout.setVerticalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20))
                    .addComponent(btnOkMembro, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(matriculaLabel)
                        .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(btnCancelarMembro)))
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diretoriaLabel)
                            .addComponent(diretoriaBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(emailLabel)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(senhaLabe)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(BtnMudarSenha)
                        .addGap(44, 44, 44)
                        .addComponent(BtnEditarMembro)))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        btnRetornar.setText("Voltar");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnRetornar)
                .addGap(14, 14, 14))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetornar))
                .addGap(43, 43, 43)
                .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diretoriaBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diretoriaBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diretoriaBoxActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void btnOkMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkMembroActionPerformed
        if( (tipo !=2 ) && (txtNome.getText().equals("") || txtMatricula.getText().equals("")||txtEmail.getText().equals("")||txtSenha.getText().equals(""))){
            JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos","Mensagem",JOptionPane.PLAIN_MESSAGE);
            txtNome.requestFocus();
            tipo = 0;
            txtNome.setEnabled(true);
            txtMatricula.setEnabled(true);
            diretoriaBox.setEnabled(true);
            txtEmail.setEnabled(true);
            txtSenha.setEnabled(true);
            txtNome.setText("");
            txtMatricula.setText("");
            txtEmail.setText("");
            txtSenha.setText("");
        }
        else if(tipo == 1){
            usuario.setSenhaMembro(txtSenha.getText());
            JOptionPane.showMessageDialog(null,"Senha alterada com sucesso","Mensagem",JOptionPane.PLAIN_MESSAGE);
            tipo = 0;
            this.setVisible(false);           
        }
        else if(tipo == 2){
            for (int i = 0; i < listaMembros.size(); i++){
                if (listaMembros.get(i).getNomeMembro().equals(txtNome.getText())){
                    if (listaMembros.get(i).getDiretoriaMembro().equals("Diretoria")){
                        JOptionPane.showMessageDialog(null,"O membro "+txtNome.getText()+" não é válido para ser editado.","Mensagem",JOptionPane.PLAIN_MESSAGE);
                        tipo = 0;                       
                        txtNome.setEnabled(true);
                        txtMatricula.setEnabled(true);
                        diretoriaBox.setEnabled(true);
                        txtEmail.setEnabled(true);
                        txtSenha.setEnabled(true);
                        txtNome.setText("");
                        txtMatricula.setText("");
                        txtEmail.setText("");
                        txtSenha.setText("");
                        break;
                    }else{
                        listaMembros.get(i).setDiretoriaMembro(diretoriaBox.getName());
                        listaMembros.get(i).setEmailInstitucionalMembro(txtEmail.getText());
                        listaMembros.get(i).setMatriculaMembro(txtMatricula.getText());
                        tipo = 0;
                        txtNome.setText("");
                        txtMatricula.setText("");
                        txtEmail.setText("");
                        txtSenha.setText("");
                        txtNome.setEnabled(true);
                        txtMatricula.setEnabled(true);
                        diretoriaBox.setEnabled(true);
                        txtEmail.setEnabled(true);
                        txtSenha.setEnabled(true);
                        JOptionPane.showMessageDialog(null,"Membro "+txtNome.getText()+" ediatdo com sucesso","Mensagem",JOptionPane.PLAIN_MESSAGE);
                        this.setVisible(false);
                        break;
                    }
     
                }
                if (i == listaMembros.size()-1){
                    JOptionPane.showMessageDialog(null,"Nenhum membro com esse nome para ser editado","Aviso",JOptionPane.PLAIN_MESSAGE);
                    txtNome.setText("");
                    txtMatricula.setText("");
                    txtEmail.setText("");
                    txtSenha.setText("");
                    txtNome.setEnabled(true);
                    txtMatricula.setEnabled(true);
                    diretoriaBox.setEnabled(true);
                    txtEmail.setEnabled(true);
                    txtSenha.setEnabled(true);
                    tipo = 0;
                }
        }
        }
        else{
            String nome = txtNome.getText();
            String matricula = txtMatricula.getText();
            String email = txtEmail.getText();
            String senha = txtSenha.getText();
            String diretoria = diretoriaBox.getSelectedItem()+ "";
            if(listaMembros.isEmpty() && (diretoria.compareTo("Diretoria") != 0)){
                JOptionPane.showMessageDialog(null,"Para garantir o bom funcionamento do Sistema, o Primeiro Membro Cadastrado deve ser um Diretor","Mensagem",JOptionPane.PLAIN_MESSAGE);
            }
            else{
            Membro membroAux = new Membro();
            if(diretoria.equals("Diretoria")){
                Diretor membro = new Diretor(nome, matricula, diretoria, email, senha, true);
                membroAux = (Membro) membro;
            }
            else if(diretoria.equals("Gerencia")){
                Gerente membro = new Gerente(nome, matricula, diretoria, email, senha, true);
                membroAux = (Membro) membro;
            }
            else{
                Membro membro = new Membro(nome, matricula, diretoria, email, senha);
                membroAux = membro;
            }
            if(listaMembros.isEmpty()){
                init.atualizaBtnCdtMemIni();
            }
            
            listaMembros.add(membroAux);

            JOptionPane.showMessageDialog(null, "Membro cadastrado com sucesso!","Mensagem",JOptionPane.INFORMATION_MESSAGE );
            
            novoCadastro = true;
            txtNome.setText("");
            txtMatricula.setText("");
            txtEmail.setText("");
            txtSenha.setText("");
            
            init.atualizaboxListaMembros();
            cdtProjeto.atualizalstMembrosProj();
            this.setVisible(false);
            }
            //Inicio.;
        }
    }//GEN-LAST:event_btnOkMembroActionPerformed

    private void BtnEditarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarMembroActionPerformed
        txtNome.setEnabled(true);
        txtMatricula.setEnabled(true);
        diretoriaBox.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSenha.setEnabled(false);
        
        tipo = 2;
        
        txtNome.setText("");
        txtMatricula.setText("");
        txtEmail.setText("");
        txtSenha.setText("");

        
    }//GEN-LAST:event_BtnEditarMembroActionPerformed

    private void BtnMudarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMudarSenhaActionPerformed
        txtNome.setEnabled(false);
        txtMatricula.setEnabled(false);
        diretoriaBox.setEnabled(false);
        txtEmail.setEnabled(false);
        txtSenha.setEnabled(true);
        
        txtNome.setText(usuario.getNomeMembro());
        txtMatricula.setText(usuario.getMatriculaMembro());
        diretoriaBox.setName(usuario.getDiretoriaMembro());
        txtEmail.setText(usuario.getEmailInstitucionalMembro());
        txtSenha.setText("");
        
        tipo = 1;
    }//GEN-LAST:event_BtnMudarSenhaActionPerformed

    private void btnCancelarMembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMembroActionPerformed
        
        btnCancelarMembro.setEnabled(true);
        btnOkMembro.setEnabled(true);
        BtnMudarSenha.setEnabled(true);
        
        if (usuario.getDiretoriaMembro().equals("Diretoria")){
            BtnEditarMembro.setEnabled(true);
        }else{
            BtnEditarMembro.setEnabled(false);
        }
        txtNome.setEnabled(true);
        txtMatricula.setEnabled(true);
        txtEmail.setEnabled(true);
        txtSenha.setEnabled(true);
        
        txtNome.setText("");
        txtMatricula.setText("");
        txtEmail.setText("");
        txtSenha.setText("");
        
        tipo = 0;
        
        txtNome.requestFocus();
    }//GEN-LAST:event_btnCancelarMembroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroMembro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroMembro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditarMembro;
    private javax.swing.JButton BtnMudarSenha;
    private javax.swing.JButton btnCancelarMembro;
    private javax.swing.JButton btnOkMembro;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JComboBox<String> diretoriaBox;
    private javax.swing.JLabel diretoriaLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel matriculaLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JPanel painelInfo;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelTitulo;
    private javax.swing.JLabel senhaLabe;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
