/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import java.util.ArrayList;
import Classes.*;
import static Telas.CadastroItem.tag;
import java.awt.List;
import java.util.Arrays;
import javax.swing.JOptionPane;
import static Telas.Inicio.listaMembros;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author lucas
 */
public class CadastroProjeto extends javax.swing.JFrame {
    
    static ArrayList<Projeto> listaProjetos;
    /**
     * Creates new form CadastroProjeto
     */
    public CadastroProjeto() {
        initComponents();
        listaProjetos = new ArrayList();
        BtnSalvar.setEnabled(true);
        BtnNovo.setEnabled(false);
        BtnPesquisar.setEnabled(true);
        BtnEditar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        
        TxtNome.setEnabled(true);
        TxtDescricao.setEnabled(true);
        lstMembrosProj.setEnabled(true);
        atualizalstMembrosProj();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelTitulo = new javax.swing.JPanel();
        Title = new javax.swing.JLabel();
        painelInfo = new javax.swing.JPanel();
        LblNomes = new javax.swing.JLabel();
        LblMembros = new javax.swing.JLabel();
        TxtNome = new javax.swing.JTextField();
        LblDescricao = new javax.swing.JLabel();
        TxtDescricao = new javax.swing.JTextField();
        BtnNovo = new javax.swing.JButton();
        BtnPesquisar = new javax.swing.JButton();
        BtnSalvar = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstMembrosProj = new javax.swing.JList<>();
        btnRetornar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setBackground(new java.awt.Color(89, 89, 94));

        painelTitulo.setBackground(new java.awt.Color(204, 204, 204));

        Title.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 51, 51));
        Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Title.setText("Cadastro projeto");

        javax.swing.GroupLayout painelTituloLayout = new javax.swing.GroupLayout(painelTitulo);
        painelTitulo.setLayout(painelTituloLayout);
        painelTituloLayout.setHorizontalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelTituloLayout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );
        painelTituloLayout.setVerticalGroup(
            painelTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelTituloLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        painelInfo.setBackground(new java.awt.Color(124, 124, 131));
        painelInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        LblNomes.setText("Nome do projeto:");

        LblMembros.setText("Membros participantes:");

        TxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TxtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNomeActionPerformed(evt);
            }
        });

        LblDescricao.setText("Descrição do projeto:");

        BtnNovo.setText("Novo");
        BtnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNovoActionPerformed(evt);
            }
        });

        BtnPesquisar.setText("Pesquisar");
        BtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPesquisarActionPerformed(evt);
            }
        });

        BtnSalvar.setText("Salvar");
        BtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalvarActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnExcluir.setText("Excluir");
        BtnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnExcluirActionPerformed(evt);
            }
        });

        lstMembrosProj.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstMembrosProj);

        javax.swing.GroupLayout painelInfoLayout = new javax.swing.GroupLayout(painelInfo);
        painelInfo.setLayout(painelInfoLayout);
        painelInfoLayout.setHorizontalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblDescricao)
                            .addComponent(LblNomes))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(painelInfoLayout.createSequentialGroup()
                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnPesquisar))
                            .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addComponent(LblMembros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInfoLayout.createSequentialGroup()
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnSalvar)
                            .addComponent(BtnNovo))
                        .addGap(29, 29, 29))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnEditar)
                            .addComponent(BtnExcluir))
                        .addContainerGap())))
        );
        painelInfoLayout.setVerticalGroup(
            painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInfoLayout.createSequentialGroup()
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblNomes)
                            .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(BtnPesquisar))))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(BtnNovo)))
                .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblDescricao)
                            .addComponent(TxtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(painelInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblMembros)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painelInfoLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(BtnSalvar)
                        .addGap(28, 28, 28)
                        .addComponent(BtnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(BtnExcluir)))
                .addContainerGap(183, Short.MAX_VALUE))
        );

        btnRetornar.setText("Voltar");
        btnRetornar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetornarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(painelPrincipalLayout.createSequentialGroup()
                        .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRetornar)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(painelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetornar))
                .addGap(18, 18, 18)
                .addComponent(painelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRetornarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetornarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnRetornarActionPerformed

    private void BtnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNovoActionPerformed
        // TODO add your handling code here:
        TxtNome.setText("");
        TxtDescricao.setText("");
        lstMembrosProj.setSelectedIndex(-1);
        
        BtnSalvar.setEnabled(true);
        BtnNovo.setEnabled(false);
        BtnPesquisar.setEnabled(false);
        BtnEditar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        
        TxtDescricao.setEnabled(true);
        lstMembrosProj.setEnabled(true);
        atualizalstMembrosProj();
    }//GEN-LAST:event_BtnNovoActionPerformed

    private void TxtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNomeActionPerformed

    private void BtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalvarActionPerformed
        TxtNome.setEnabled(true);
        TxtDescricao.setEnabled(true);
        lstMembrosProj.setEnabled(false);
        
        String nom = TxtNome.getText();
        String desc = TxtDescricao.getText();
        ArrayList<Membro> membrosProj = new ArrayList<Membro>();
        int[] indMembros = lstMembrosProj.getSelectedIndices();
        for(int i = 0; i < indMembros.length;i++){
            membrosProj.add(listaMembros.get(indMembros[i]));
        }
              
        Projeto projeto = new Projeto(nom,desc,membrosProj);
        for(int i = 0; i < listaProjetos.size();i++){
            if(listaProjetos.get(i).getNome().equals(nom)){
                listaProjetos.remove(i);
            }
        }
        listaProjetos.add(projeto);
        atualizalstMembrosProj();
        TxtNome.setText("");
        TxtDescricao.setText("");
        lstMembrosProj.setSelectedIndex(-1);
        BtnSalvar.setEnabled(false);
        BtnNovo.setEnabled(true);
        BtnPesquisar.setEnabled(true);
        BtnEditar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        
        JOptionPane.showMessageDialog(null, "Projeto cadastrado", "Aviso", JOptionPane.INFORMATION_MESSAGE);               
        
    }//GEN-LAST:event_BtnSalvarActionPerformed

    private void BtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPesquisarActionPerformed
        BtnEditar.setEnabled(true);
        BtnSalvar.setEnabled(false);
        BtnNovo.setEnabled(true);
        BtnPesquisar.setEnabled(true);
        BtnExcluir.setEnabled(true);
        
        TxtNome.setEnabled(true);
        TxtDescricao.setEnabled(false);
        lstMembrosProj.setEnabled(false);
        
        if (listaProjetos.isEmpty()){
            JOptionPane.showMessageDialog(null, "Nenhum projeto está cadastrado.", "Aviso", JOptionPane.PLAIN_MESSAGE); 
            TxtNome.setText("");
            TxtDescricao.setText("");
            atualizalstMembrosProj();
        }
        if(TxtNome.getText().equals("")){
            JOptionPane.showMessageDialog(null,"O nome ser informado","Aviso",JOptionPane.PLAIN_MESSAGE);
        }
        else{
            
            Projeto proj;
            String nome = "", descricao = "";
            String nom = TxtNome.getText();
            String[] membrosProjPesq = {""};
            for (int i = 0; i < listaProjetos.size(); i++){
                proj = listaProjetos.get(i);
                if (nom == null ? proj.getNome()== null : nom.equals(proj.getNome())){
                    nome = String.valueOf(proj.getNome());
                    descricao = String.valueOf(proj.getDescricao());
                    atualizalstMembrosProj();
                }
            }
            if (nome.equals("")){
                JOptionPane.showMessageDialog(null,"Nenhum projeto com este nome encontrado","Aviso",JOptionPane.PLAIN_MESSAGE);
                TxtNome.setText("");
                TxtDescricao.setText("");
                lstMembrosProj.setModel(new DefaultComboBoxModel<String>(membrosProjPesq));
            }else{
                TxtNome.setText(nome);
                TxtDescricao.setText(descricao);
                atualizalstMembrosProj();
                
            }

        }

            // TODO add your handling code here:
    }//GEN-LAST:event_BtnPesquisarActionPerformed

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
        
        TxtNome.setEnabled(false);
        TxtDescricao.setEnabled(true);
        lstMembrosProj.setEnabled(true);
        atualizalstMembrosProj();
        
        BtnEditar.setEnabled(false);
        BtnSalvar.setEnabled(true);
        BtnNovo.setEnabled(false);
        BtnPesquisar.setEnabled(false);
        
       
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void BtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnExcluirActionPerformed
        BtnSalvar.setEnabled(false);
        BtnNovo.setEnabled(true);
        BtnPesquisar.setEnabled(true);
        BtnEditar.setEnabled(false);
        BtnExcluir.setEnabled(false);
        
        for (int i = 0; i < listaProjetos.size(); i++){
            if(listaProjetos.get(i).getNome().equals(TxtNome.getText())){
                listaProjetos.remove(i);
            }
        }
        TxtNome.setText("");
        TxtDescricao.setText("");
        lstMembrosProj.setSelectedIndex(-1);
        
        TxtNome.setEnabled(true);
        TxtDescricao.setEnabled(true);
        lstMembrosProj.setEnabled(true);
    }//GEN-LAST:event_BtnExcluirActionPerformed
    public void atualizalstMembrosProj(){
        if(listaMembros != null){            
            String[] membrosAux = new String[listaMembros.size()];
            for(int i = 0; i < listaMembros.size();i++){
                membrosAux[i] = listaMembros.get(i).getNomeMembro();
            }
            lstMembrosProj.setModel(new DefaultComboBoxModel<>(membrosAux));
        }
        else{
            String[] vazio = {"","","","",""};
            lstMembrosProj.setModel(new DefaultComboBoxModel<>(vazio));
        }
        lstMembrosProj.setSelectedIndex(-1);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProjeto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProjeto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnExcluir;
    private javax.swing.JButton BtnNovo;
    private javax.swing.JButton BtnPesquisar;
    private javax.swing.JButton BtnSalvar;
    private javax.swing.JLabel LblDescricao;
    private javax.swing.JLabel LblMembros;
    private javax.swing.JLabel LblNomes;
    private javax.swing.JLabel Title;
    private javax.swing.JTextField TxtDescricao;
    private javax.swing.JTextField TxtNome;
    private javax.swing.JButton btnRetornar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstMembrosProj;
    private javax.swing.JPanel painelInfo;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelTitulo;
    // End of variables declaration//GEN-END:variables
}
