/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;
import Classes.Chamado;
import Classes.Cliente;
import java.awt.*;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author leoma
 */
public class CadastroCliente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroCliente
     */
    static ArrayList<Cliente> Clientes;
    static ArrayList<Chamado> Chamados;
    String btn;
    int indexAux = -1;
    CadastroChamado chm;
    boolean ChamadoAtivo = false;
    public CadastroCliente() {
        
        initComponents();
       
       Clientes = new ArrayList();
       Chamados = new ArrayList();
       btnCadastrar.setEnabled(true);
       btnCancelar.setEnabled(false);
       btnEditar.setEnabled(false);
       btnExcluir.setEnabled(false);
       btnOK.setEnabled(false);
       btnSalvar.setEnabled(false);
       btnPesquisar.setEnabled(true);
       
       txtCPF.setEnabled(false);
       txtId.setEnabled(false);
       txtNome.setEnabled(false);
       txtRG.setEnabled(false);
       txtTelefone.setEnabled(false);
    }
    
    public void carregarTabela(){
        DefaultTableModel modelo = new DefaultTableModel(new Object[] {"Id","RG","Nome","Telefone","CPF"},0);
        
        for(int i = 0; i < Clientes.size(); i++){
            Object linha[] = new Object[]{Clientes.get(i).getId(),Clientes.get(i).getRG(),Clientes.get(i).getNome(),Clientes.get(i).getTelefone(),Clientes.get(i).getCPF()};
            modelo.addRow(linha);        
        }
        Tabela.setModel(modelo);
        
        Tabela.getColumnModel().getColumn(0).setPreferredWidth(5);
        Tabela.getColumnModel().getColumn(1).setPreferredWidth(50);
        Tabela.getColumnModel().getColumn(2).setPreferredWidth(50);
        Tabela.getColumnModel().getColumn(3).setPreferredWidth(50);
        Tabela.getColumnModel().getColumn(4).setPreferredWidth(50);
        Tabela.getColumnModel().getColumn(5).setPreferredWidth(50);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane1 = new java.awt.ScrollPane();
        lbId = new javax.swing.JLabel();
        lbRG = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbCPF = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtRG = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        btnOK = new javax.swing.JToggleButton();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnPesquisar = new javax.swing.JButton();
        Painel = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        ImgPrincCliente = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        Barra = new javax.swing.JMenuBar();
        Menu = new javax.swing.JMenu();
        btnNovoChamado = new javax.swing.JMenuItem();
        Sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbId.setText("ID");

        lbRG.setText("RG");

        lbNome.setText("Nome");

        lbTelefone.setText("CPF");

        lbCPF.setText("Telefone");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        btnSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Salvar.png"))); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Cadastrar.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnCadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Novo.png"))); // NOI18N
        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Editar.png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Excluir.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        btnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Pesquisar.png"))); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},

            },
            new String [] {
                "ID", "RG", "Nome", "Telefone", "CPF"
            }
        ));
        Tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaMouseClicked(evt);
            }
        });
        Painel.setViewportView(Tabela);

        ImgPrincCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PrincipalCliente.png"))); // NOI18N

        lbTitulo.setFont(new java.awt.Font("Swis721 BlkEx BT", 0, 36)); // NOI18N
        lbTitulo.setText("Cadastro de Cliente");

        Menu.setText("Opções");
        Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuActionPerformed(evt);
            }
        });

        btnNovoChamado.setText("Novo Chamado");
        btnNovoChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoChamadoActionPerformed(evt);
            }
        });
        Menu.add(btnNovoChamado);

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        Menu.add(Sair);

        Barra.add(Menu);

        setJMenuBar(Barra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lbCPF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbRG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lbTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(80, 80, 80)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(lbTitulo)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(ImgPrincCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 144, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Painel)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTitulo)
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbId)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbRG)
                            .addComponent(txtRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbNome)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbCPF)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTelefone)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOK)))
                    .addComponent(ImgPrincCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnCancelar)
                    .addComponent(btnCadastrar)
                    .addComponent(btnEditar)
                    .addComponent(btnExcluir)
                    .addComponent(btnPesquisar))
                .addGap(33, 33, 33)
                .addComponent(Painel, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoChamadoActionPerformed
        // TODO add your handling code here:
        ChamadoAtivo = true;
        chm = new CadastroChamado();
        chm.setVisible(true);
        chm.carregarTabela2();
        //new CadastroChamado().setVisible( true );
    }//GEN-LAST:event_btnNovoChamadoActionPerformed

    private void MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_SairActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
       btn = "novo";
       btnCadastrar.setEnabled(false);
       btnCancelar.setEnabled(true);
       btnEditar.setEnabled(false);
       btnExcluir.setEnabled(false);
       btnOK.setEnabled(false);
       btnSalvar.setEnabled(true);
       btnPesquisar.setEnabled(false);
       
       txtCPF.setEnabled(true);
       txtId.setEnabled(true);
       txtNome.setEnabled(true);
       txtRG.setEnabled(true);
       txtTelefone.setEnabled(true);
       
       txtId.requestFocus();
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
       txtCPF.setText("");
       txtId.setText("");
       txtNome.setText("");
       txtRG.setText("");
       txtTelefone.setText("");
       
       btnCadastrar.setEnabled(true);
       btnCancelar.setEnabled(false);
       btnEditar.setEnabled(false);
       btnExcluir.setEnabled(false);
       btnOK.setEnabled(false);
       btnSalvar.setEnabled(false);
       btnPesquisar.setEnabled(true);
       
       txtCPF.setEnabled(false);
       txtId.setEnabled(false);
       txtNome.setEnabled(false);
       txtRG.setEnabled(false);
       txtTelefone.setEnabled(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        boolean flagAux;
        try{
            Integer.parseInt(txtId.getText());
            flagAux = true;
        }
        catch(NumberFormatException e){
            flagAux = false;
        }
        if(txtCPF.getText().equals("")||txtId.getText().equals("")||txtNome.getText().equals("")||txtRG.getText().equals("")||txtTelefone.getText().equals("") || !flagAux){
            JOptionPane.showMessageDialog(null, "Campos não Preenchidos ou Preenchidos Incorretamente","Mensagem", JOptionPane.PLAIN_MESSAGE);
            txtId.requestFocus();
        }
        else{
        String cpf = txtCPF.getText();
        int id = Integer.parseInt(txtId.getText());
        String nome = txtNome.getText();
        String rg = txtRG.getText();
        String telefone = txtTelefone.getText();
        
        if(btn.equals("novo")){
        Cliente clt = new Cliente(id,rg,nome,telefone,cpf);
        Clientes.add(clt);
        JOptionPane.showMessageDialog(null, "Cliente Cadastrado","Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else if(btn.equals("editar")){
            int ind = Tabela.getSelectedRow();
            if(ind != -1){
                
                if(ChamadoAtivo){
                chm.excluirTxtId(Clientes.get(ind));
                }
                Clientes.get(ind).setId(id);
                Clientes.get(ind).setRG(rg);
                Clientes.get(ind).setNome(nome);
                Clientes.get(ind).setTelefone(telefone);
                Clientes.get(ind).setCPF(cpf);
                
                if(ChamadoAtivo){
                chm.adicionarTxtId(Clientes.get(ind));
                }
            }
            else{
                if(ChamadoAtivo){
                Cliente clt = Clientes.get(indexAux);
                chm.excluirTxtId(clt);
                }
                Clientes.get(indexAux).setId(id);
                Clientes.get(indexAux).setRG(rg);
                Clientes.get(indexAux).setNome(nome);
                Clientes.get(indexAux).setTelefone(telefone);
                Clientes.get(indexAux).setCPF(cpf);
                if(ChamadoAtivo){
                chm.adicionarTxtId(Clientes.get(indexAux));
                }
                
                indexAux = -1;
            }
            
        }
        txtCPF.setText("");
        txtId.setText("");
        txtNome.setText("");
        txtRG.setText("");
        txtTelefone.setText("");
       
        btnCadastrar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnPesquisar.setEnabled(true);
       
        txtCPF.setEnabled(false);
        txtId.setEnabled(false);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        carregarTabela();
        if(ChamadoAtivo){
            chm.carregarTabela2();
        }

        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void TabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaMouseClicked
        // TODO add your handling code here:
        int i = Tabela.getSelectedRow();
        
        if(i >= 0 && i < Clientes.size()){
            Cliente client = Clientes.get(i);
            txtId.setText(String.valueOf(client.getId()));
            txtRG.setText(client.getRG());
            txtNome.setText(client.getNome());
            txtTelefone.setText(client.getTelefone());
            txtCPF.setText(client.getCPF());
        }
        
        btnCadastrar.setEnabled(false);
        btnCancelar.setEnabled(false);
        btnEditar.setEnabled(true);
        btnExcluir.setEnabled(true);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnPesquisar.setEnabled(true);
        
        
    }//GEN-LAST:event_TabelaMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        btn = "editar";
                
        btnCadastrar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(true);
        btnPesquisar.setEnabled(false);
       
        txtCPF.setEnabled(true);
        txtId.setEnabled(true);
        txtNome.setEnabled(true);
        txtRG.setEnabled(true);
        txtTelefone.setEnabled(true);
        
        txtId.requestFocus();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        int i = Tabela.getSelectedRow();
        if(i >= 0 && i < Clientes.size()){
            Cliente clt = Clientes.get(i);
            Clientes.remove(i);
            if(ChamadoAtivo){
            chm.excluirTxtId(clt);
            }
            for(int j = 0; j < Chamados.size();j++){
            if(Chamados.get(j).getClt().getId() == clt.getId()){
                Chamados.remove(j);
            }
        }
            
        }
        else if(indexAux >= 0 && indexAux < Clientes.size()){
            Cliente clt = Clientes.get(indexAux);
            Clientes.remove(indexAux);
            if(ChamadoAtivo){
            chm.excluirTxtId(clt);
            }
            indexAux = -1;
           for(int j = 0; j < Chamados.size();j++){
            if(Chamados.get(j).getClt().getId() == clt.getId()){
                Chamados.remove(j);
            }
        }
        }

        txtCPF.setText("");
        txtId.setText("");
        txtNome.setText("");
        txtRG.setText("");
        txtTelefone.setText("");
       
        btnCadastrar.setEnabled(true);
        btnCancelar.setEnabled(false);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnOK.setEnabled(false);
        btnSalvar.setEnabled(false);
        btnPesquisar.setEnabled(true);
       
        txtCPF.setEnabled(false);
        txtId.setEnabled(false);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        carregarTabela();
        if(ChamadoAtivo){
            chm.carregarTabela2();
        }
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        if(Clientes.isEmpty()){
            JOptionPane.showMessageDialog(null, "Não há Clientes Cadastrados","Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else{
        txtCPF.setText("");
        txtId.setText("");
        txtNome.setText("");
        txtRG.setText("");
        txtTelefone.setText("");
       
        btnCadastrar.setEnabled(false);
        btnCancelar.setEnabled(true);
        btnEditar.setEnabled(false);
        btnExcluir.setEnabled(false);
        btnOK.setEnabled(true);
        btnSalvar.setEnabled(false);
        btnPesquisar.setEnabled(false);
       
        txtCPF.setEnabled(true);
        txtId.setEnabled(false);
        txtNome.setEnabled(false);
        txtRG.setEnabled(false);
        txtTelefone.setEnabled(false);
        
        txtCPF.requestFocus();
        }
    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        // TODO add your handling code here:
        String idStr = "";
        String rgStr = "";
        String nomeStr = "";
        String telefoneStr = "";
        String cpfStr = "";
        if(txtCPF.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Informe o CPF do Cliente","Mensagem", JOptionPane.PLAIN_MESSAGE);
        }
        else{
            Cliente client;
            String cpf = txtCPF.getText();
            
            for(int i = 0; i < Clientes.size(); i++){
                client = Clientes.get(i);
                
                if(cpf.equals(client.getCPF()) ){
                    indexAux = i;
                    idStr = String.valueOf(client.getId());
                    rgStr =client.getRG();
                    nomeStr =client.getNome();
                    telefoneStr = client.getTelefone();
                    cpfStr = client.getCPF();
                    
                }
            }
            if(cpfStr.equals("")){
                JOptionPane.showMessageDialog(null, "CPF inexistente","Mensagem", JOptionPane.PLAIN_MESSAGE);
            }
            else{
                txtId.setText(idStr);
                txtRG.setText(rgStr);
                txtNome.setText(nomeStr);
                txtTelefone.setText(telefoneStr);
                txtCPF.setText(cpfStr);
                
                btnCadastrar.setEnabled(false);
                btnCancelar.setEnabled(false);
                btnEditar.setEnabled(true);
                btnExcluir.setEnabled(true);
                btnOK.setEnabled(false);
                btnSalvar.setEnabled(false);
                btnPesquisar.setEnabled(false);
            }
        }
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra;
    private javax.swing.JLabel ImgPrincCliente;
    private javax.swing.JMenu Menu;
    private javax.swing.JScrollPane Painel;
    private javax.swing.JMenuItem Sair;
    private javax.swing.JTable Tabela;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JMenuItem btnNovoChamado;
    private javax.swing.JToggleButton btnOK;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbId;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbRG;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTitulo;
    private java.awt.ScrollPane scrollPane1;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtRG;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
